#!/usr/bin/env python3
"""
把 scenarios/ 下的题材与共享结局注入离线副本，供 file:// 直接双击打开时使用
（浏览器在 file:// 协议下禁止 fetch 本地 JSON）。

用法：python3 tools/embed-scenarios.py
约定：改完 scenarios/*.json 后跑一次本脚本，再提交生成的文件。

产物（两者都必须提交，否则 file:// 双击打不开）：
  index.html          仅内嵌 manifest（~2KB）；endings 拆到 embed/endings.js
  embed/endings.js    window.CHOICES_EMBEDDED.endings
  embed/<id>.js       window.CHOICES_EMBEDDED.scenarios["<id>"]

为什么场景要拆成独立文件（性能，issue #7）
----------------------------------------------
早期把 6 个场景全部内嵌进 index.html（290KB）。浏览器必须先解析完这 284KB
JSON 才触发 DOMContentLoaded，实测 domInteractive=1493ms、domComplete=3061ms——
开始画面的题材卡因此要等一秒半才出现。实测 JSON.parse 本身只要 0.6ms，
瓶颈从来不是解析，而是「必须等全部内容解析完」这件事本身。

拆开后 index.html 只剩 ~10KB，首屏立刻可交互；开始画面先用 manifest 里的
title/hook 渲染（这部分数据本来就在 manifest 里），玩家点 PRESS START 后再
按需加载那一个场景文件（~42KB）——把 1.5 秒的首屏等待换成按需的一小段加载。

file:// 下不能 fetch，但可以动态注入 <script src>（已实测可用），所以
embed/*.js 用普通 <script> 而非 ES module（module 在 file:// 下会被 CORS 拦掉）。

幂等性（重要）：按文件名整体覆盖写入，而不是靠一次性占位符——占位符在第一次
运行后就被消费掉，会导致后续每次运行都「看似成功、实则没有更新」（这个坑真实
发生过）。脚本最后会重新解析所有产物并与源文件逐一比对，任何不一致直接报错退出。
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCEN = ROOT / "scenarios"
INDEX = ROOT / "index.html"
EMBED = ROOT / "embed"

BANNER = (
    "// GENERATED by tools/embed-scenarios.py from scenarios/{src} — do not edit by hand.\n"
    "// Offline copy used when the page is opened directly (file://), where fetch of local\n"
    "// JSON is blocked by the browser. Served normally on a static host / GitHub Pages.\n"
)


def load(rel):
    return json.loads((SCEN / rel).read_text(encoding="utf-8"))


def sub_once(html, pattern, repl, label):
    """re.sub 且必须恰好命中一次，否则报错退出（防止静默失效）。"""
    html, n = re.subn(pattern, repl, html, flags=re.S)
    if n != 1:
        sys.exit(f"ERROR: {label} 命中 {n} 次（应为 1），index.html 结构可能已变化。")
    return html


def js_for(data, src_name, varname):
    """把 Python 对象写成 JS 字面量赋值语句。

    每个数据文件都自带幂等初始化（先确保 window.CHOICES_EMBEDDED 存在），
    这样任何一个文件都可以作为第一个被注入的脚本，不会依赖单独的 bootstrap 文件
    ——曾经依赖 bootstrap.js，结果某一版 player.js 忘了先加载它，
    所有数据文件都在 undefined.scenarios 上抛错，场景静默加载失败。
    """
    body = json.dumps(data, ensure_ascii=False, indent=2)
    head = (BANNER.format(src=src_name) +
            "window.CHOICES_EMBEDDED = window.CHOICES_EMBEDDED || { endings: null, scenarios: {} };\n")
    return head + f"window.{varname} = {body};\n"


def main():
    manifest = load("manifest.json")
    # endings-core.json 顶层包了一层 {"endings": {...}}，但运行时约定 coreEndings
    # 就是那9 个结局组成的字典（player.js 里 scenario.endings = coreEndings）。
    # 若直接把整个文件塞进去，运行时会拿到 endings.endings，多一层包装，
    # 校验器就会报「endings 缺少 condition」。这里剥掉外层。
    endings = load(manifest["endings"])
    if set(endings.keys()) == {"endings"}:
        endings = endings["endings"]

    scenario_data = {m["id"]: load(m["file"]) for m in manifest["scenarios"]}
    if not EMBED.is_dir():
        EMBED.mkdir(parents=True)

    # ---- 产物 1: embed/*.js（整体覆盖写入，天然幂等） ----
    (EMBED / "endings.js").write_text(
        js_for(endings, manifest["endings"], "CHOICES_EMBEDDED.endings"), encoding="utf-8")
    (EMBED / "endings.js").write_text(
        js_for(endings, manifest["endings"], "CHOICES_EMBEDDED.endings"), encoding="utf-8")
    for meta in manifest["scenarios"]:
        sid = meta["id"]
        (EMBED / f"{sid}.js").write_text(
            js_for(scenario_data[sid], meta["file"], f'CHOICES_EMBEDDED.scenarios["{sid}"]'),
            encoding="utf-8")
        print(f"  embed/{sid}.js  ({meta['file']})")

    # ---- 产物 2: index.html 只保留 manifest 内嵌块，移除场景块 ----
    html = INDEX.read_text(encoding="utf-8")
    html = sub_once(
        html,
        r'(<script type="application/json" id="embedded-manifest">)(.*?)(</script>)',
        lambda m: m.group(1) + "\n" + json.dumps(manifest, ensure_ascii=False, indent=2) + "\n  " + m.group(3),
        "embedded-manifest",
    )
    # 场景块与内嵌 endings 块若仍存在（从旧版升级），整块删除；不存在则跳过。
    # 注意：这两条正则必须【非贪婪】。贪婪版本（.* 跨行）会从第一个 <script ...>
    # 一路吞到最后一个 </script>，把夹在中间的 embedded-manifest 块一起删掉——
    # 这个坑真实发生过：index.html 里 manifest 消失，页面直接白屏报
    # "Cannot read properties of null (reading 'scenarios')"。
    before = len(html)
    html = re.sub(
        r'\n?[ \t]*<script type="application/json" data-scenario-id="[^"]+">.*?</script>',
        "", html, flags=re.S)
    html = re.sub(
        r'\n?[ \t]*<script type="application/json" id="embedded-endings">.*?</script>',
        "", html, flags=re.S)
    removed = (before - len(html)) > 0

    # manifest 块必须还在，否则下面写入等于白写——立刻停下，别产出一个坏页面。
    if 'id="embedded-manifest"' not in html:
        sys.exit("ERROR: embedded-manifest 块丢失，已中止（index.html 未写盘）。"
                 "通常是删除用的正则贪婪匹配过头了。")

    INDEX.write_text(html, encoding="utf-8")
    print(f"  index.html: manifest inlined, scenario/endings blocks removed (changed={removed})")

    # ---- 事后校验：所有产物必须与源文件完全一致 ----
    final = INDEX.read_text(encoding="utf-8")
    problems = []

    m = re.search(r'<script type="application/json" id="embedded-manifest">(.*?)</script>', final, flags=re.S)
    if not m or json.loads(m.group(1)) != manifest:
        problems.append("index.html:embedded-manifest")

    def read_js(path):
        txt = (ROOT / path).read_text(encoding="utf-8")
        mo = re.search(r"= (\{.*\}|\[.*\]);\s*$", txt, flags=re.S)
        return json.loads(mo.group(1)) if mo else None

    if read_js("embed/endings.js") != endings:
        problems.append("embed/endings.js")
    for meta in manifest["scenarios"]:
        if read_js(f'embed/{meta["id"]}.js') != scenario_data[meta["id"]]:
            problems.append(f'embed/{meta["id"]}.js')

    if problems:
        sys.exit("ERROR: 以下产物与源文件不一致: " + ", ".join(problems))

    kb = len(final) // 1024
    print(f"done: index.html {kb} KB (was 290 KB) · embed/ 共 "
          f"{sum(f.stat().st_size for f in EMBED.glob('*.js')) // 1024} KB · 全部产物已与源文件核对一致")


if __name__ == "__main__":
    main()